Update requirements.txt
"AttributeError: module 'numpy' has no attribute 'object'. `np.object` was a deprecated" So I had to downgrade the version of numpy which has object attribute.